const myApps = [
    // --- Google Ecosystem ---
    { name: "Google One", pkg: "com.google.android.apps.subscriptions.red" },
    { name: "Google Meet", pkg: "com.google.android.apps.tachyon" },
    { name: "YouTube", pkg: "com.google.android.youtube" },
    { name: "YouTube Music", pkg: "com.google.android.apps.youtube.music" },
    { name: "Google Photos", pkg: "com.google.android.apps.photos" },
    { name: "Keep Notes", pkg: "com.google.android.keep" },
    { name: "Google TV", pkg: "com.google.android.videos" },
    { name: "Google News", pkg: "com.google.android.apps.magazines" },
    { name: "Google Podcasts", pkg: "com.google.android.apps.podcasts" },
    { name: "Google Assistant", pkg: "com.google.android.apps.googleassistant" },
    { name: "Google Search", pkg: "com.google.android.googlequicksearchbox" },
    { name: "Google Maps", pkg: "com.google.android.apps.maps" },
    { name: "Google Lens", pkg: "com.google.ar.lens" },
    { name: "Google Calendar", pkg: "com.google.android.calendar" },
    { name: "Android Auto", pkg: "com.google.android.projection.gearhead" },
    { name: "Digital Wellbeing", pkg: "com.google.android.apps.wellbeing" },
    { name: "Device Health Services", pkg: "com.google.android.apps.turbo" },
    { name: "Google Feedback", pkg: "com.google.android.feedback" },
    { name: "Google Contact Keys", pkg: "com.google.android.contactkeys" },
    { name: "Google Safety Core", pkg: "com.google.android.safetycore" },
    { name: "Google Play Services for AR", pkg: "com.google.ar.core" },
    { name: "Google Setup Wizard", pkg: "com.google.android.setupwizard" },
    { name: "Pixel Setup Wizard", pkg: "com.google.android.pixel.setupwizard" },
    { name: "Google Weather", pkg: "com.google.android.apps.weather" },
    { name: "Google Docs", pkg: "com.google.android.apps.docs" },
    { name: "Google Gemini", pkg: "com.google.android.apps.bard" },
    { name: "Data Restore Tool", pkg: "com.google.android.apps.restore" },
    { name: "Google Recorder", pkg: "com.google.android.apps.recorder" },
    { name: "Gmail", pkg: "com.google.android.gm" },
    { name: "Google Wallet", pkg: "com.google.android.apps.walletnfcrel" },
    { name: "Google Speech Services", pkg: "com.google.android.tts" },
    { name: "Google Hangouts", pkg: "com.google.android.talk" },
    { name: "Google Play Music", pkg: "com.google.android.music" },
    { name: "Google Play Books", pkg: "com.google.android.apps.books" },
    { name: "Cloud Print", pkg: "com.google.android.apps.cloudprint" },
    { name: "Google Currents", pkg: "com.google.android.apps.currents" },
    { name: "Google Fit", pkg: "com.google.android.apps.fitness" },
    { name: "Google Plus", pkg: "com.google.android.apps.plus" },
    { name: "Google Wallpapers", pkg: "com.google.android.apps.wallpaper" },
    { name: "Chrome", pkg: "com.android.chrome" },
    { name: "Carrier Services", pkg: "com.google.android.ims" },
    { name: "Talkback", pkg: "com.google.android.marvin.talkback" },
    { name: "Pixel Migrate", pkg: "com.google.android.apps.pixelmigrate" },
    { name: "Files by Google", pkg: "com.google.android.apps.nbu.files" },
    { name: "Search Selector", pkg: "com.google.android.apps.setupwizard.searchselector" },
    { name: "Google Calculator", pkg: "com.google.android.calculator" },
    { name: "Google One Time Initializer", pkg: "com.google.android.onetimeinitializer" },

    // --- Xiaomi / MIUI / HyperOS Ecosystem ---
    { name: "Analytics", pkg: "com.miui.analytics" },
    { name: "App Vault", pkg: "com.miui.personalassistant" },
    { name: "Backup", pkg: "com.miui.backup" },
    { name: "Mi Browser", pkg: "com.mi.globalbrowser" },
    { name: "CatchLog", pkg: "com.bsp.catchlog" },
    { name: "Cleaner", pkg: "com.miui.cleanmaster" },
    { name: "Compass", pkg: "com.miui.compass" },
    { name: "Downloads", pkg: "com.android.providers.downloads.ui" },
    { name: "FM Radio", pkg: "com.miui.fm" },
    { name: "Games", pkg: "com.xiaomi.glgm" },
    { name: "GetApps", pkg: "com.xiaomi.mipicks" },
    { name: "Hybrid Accessory", pkg: "com.miui.hybrid.accessory" },
    { name: "MSA", pkg: "com.miui.msa.global" },
    { name: "Mi Credit", pkg: "com.micredit.in" },
    { name: "ShareMe (Mi Drop)", pkg: "com.xiaomi.midrop" },
    { name: "Mi Mover", pkg: "com.miui.huanji" },
    { name: "Mi Pay", pkg: "com.mipay.wallet.in" },
    { name: "Mi Share", pkg: "com.miui.mishare.connectivity" },
    { name: "Mi Recycle", pkg: "com.xiaomi.mirecycle" },
    { name: "MiConnectService", pkg: "com.xiaomi.mi_connect_service" },
    { name: "MiPlayClient", pkg: "com.xiaomi.miplay_client" },
    { name: "Wallpaper Carousel", pkg: "com.miui.android.fashiongallery" },
    { name: "MiuiDaemon", pkg: "com.miui.daemon" },
    { name: "Music", pkg: "com.miui.player" },
    { name: "NextPay", pkg: "com.miui.nextpay" },
    { name: "Notes", pkg: "com.miui.notes" },
    { name: "PAI (Joyose)", pkg: "com.xiaomi.joyose" },
    { name: "Partner Bookmarks", pkg: "com.android.bookmarkprovider" },
    { name: "Quick Apps", pkg: "com.miui.hybrid" },
    { name: "Quick Ball", pkg: "com.miui.touchassistant" },
    { name: "Search", pkg: "com.android.quicksearchbox" },
    { name: "SMS Extra", pkg: "com.miui.smsextra" },
    { name: "Scanner", pkg: "com.xiaomi.scanner" },
    { name: "Services & Feedback", pkg: "com.miui.miservice" },
    { name: "Weather", pkg: "com.miui.weather2" },
    { name: "Yellow Pages", pkg: "com.miui.yellowpage" },
    { name: "Sim Activate Service", pkg: "com.xiaomi.simactivate.service" },
    { name: "Service Framework", pkg: "com.xiaomi.xmsf" },
    { name: "Cloud Sync", pkg: "com.miui.micloudsync" },
    { name: "System Ad Solution", pkg: "com.miui.systemAdSolution" },
    { name: "Miui Phrase", pkg: "com.miui.phrase" },
    { name: "Soter Service", pkg: "com.tencent.soter.soterserver" },
    { name: "Mi Cloud Sync", pkg: "com.miui.micloudsync" },
    { name: "Mi Bug Report", pkg: "com.miui.bugreport" },
    { name: "Mi File Manager", pkg: "com.mi.android.globalFileexplorer" },
    { name: "Mi Video", pkg: "com.miui.videoplayer" },
    { name: "Mi Live Assistant", pkg: "com.mi.liveassistant" },
    { name: "Mi User Guide", pkg: "com.miui.userguide" },
    { name: "Mi Health", pkg: "com.mi.health" },
    { name: "Xiaomi Mirror", pkg: "com.xiaomi.mirror" },

    // --- Facebook / Meta ---
    { name: "Facebook System", pkg: "com.facebook.system" },
    { name: "Facebook Services", pkg: "com.facebook.services" },
    { name: "Facebook App Manager", pkg: "com.facebook.appmanager" },
    { name: "Facebook App", pkg: "com.facebook.katana" }
];
